フォームの課題
futaba96/php_exercise01 pull request #6
Opened 2022-09-03 03:44 UTC by futaba96

### カリキュラムURL
https://github.com/elites-team/2months_course/blob/main/doc/06_php/exercise01_cli/06_form/01.md

### 課題番号
フォームの課題(1、3、4、5)

### 現在の状況
**1.フォームの作成**
先頭を改行したい場合、\nでは改行することはできないのでしょうか？
(32行目の echo "\n私は{$msg}歳です”; について)
送信を押したら、一行空いて[私は○歳です]と出力されるようにしたいです。

<img width="129" alt="スクリーンショット 2022-09-03 11 52 26" src="https://user-images.githubusercontent.com/108456982/188253118-2b1824e5-01a0-412d-844f-6f155cf863f1.png">

**3. バリデーションの作成**
(1) labelのfor属性について(31行目)
現在、< label for="" >年齢< /label >と書いているのですが、 for=“”がない場合は、
< label >ではなく、< p >などを使用しても良いのでしょうか？
もし、< label >を使用するべき理由があれば教えていただきたいです。

(2)空欄で送信をした場合について
 if (isset($_POST['age’]))と指定しても、空欄で送信を押した際に、
送信ボタンの下に、[私は歳です]と出力されてしまいます。 

<img width="228" alt="スクリーンショット 2022-09-03 11 39 29" src="https://user-images.githubusercontent.com/108456982/188253194-5a92dcec-27c3-456f-a3fe-8079c750663b.png">

(3) if (!empty($err_msg)) について
26行目のコードに関して、なぜif (!empty($err_msg))になるのか教えてください😭
$err_msgを出力させるのは、if (empty($msg))の時ではないのでしょうか？😫😫

**4. GETメソッド**
どのようにコードを書けば良いのかがわからないです😢
単体であれば、echo $num1 + $num2;やecho $num1 * $num2で実行ができたのですが、
$operatorの値が複数ある際の書き方がわかりません。。。

**5. 複数のフォーム**
(1)URLを開くと、52行目がエラーと書いてあります。

<img width="1126" alt="スクリーンショット 2022-09-03 11 39 59" src="https://user-images.githubusercontent.com/108456982/188253664-1c498db6-e78c-4fcd-aee6-aa0e0fb7ebd9.png">

変数に変数を代入する際、「$sum = $num1 + $num2 + $num3; 」の書き方のどこがエラーの原因なのかを教えていただきたいです。

(2)XSS対策
XSS対策について完全に理解ができないのですが、変数に関数htmlentities()を代入するということでしょうか？
また、変数が複数ある場合は、全ての変数にhtmlentities()を利用するべきなのでしょうか？

2022-09-03 05:29 UTC, kazu-taka commented
@futaba96 
>先頭を改行したい場合、\nでは改行することはできないのでしょうか？
(32行目の echo "\n私は{$msg}歳です”; について)
送信を押したら、一行空いて[私は○歳です]と出力されるようにしたいです。

HTMLでの改行は`<br>`タグになるので、`<br>`タグを入れることで改行することは可能です✨
または、余白を入れるのであれば、CSSで`margin`や`padding`を設定するのも良いと思います😊

2022-09-03 05:32 UTC, kazu-taka commented
@futaba96 
>現在、< label for="" >年齢< /label >と書いているのですが、 for=“”がない場合は、
< label >ではなく、< p >などを使用しても良いのでしょうか？
もし、< label >を使用するべき理由があれば教えていただきたいです。

今回は`for`属性が空ですので、pタグでも問題ないですが、フォームの部品に関する説明文はlabelを使用した方が良いので、なるべくlabelタグを使用して、装飾はCSSで行うのが良いと思います😊

2022-09-03 05:34 UTC, kazu-taka commented
@futaba96 
>26行目のコードに関して、なぜif (!empty($err_msg))になるのか教えてください😭
$err_msgを出力させるのは、if (empty($msg))の時ではないのでしょうか？😫😫

入力した値が空っぽの時は、以下の処理でエラーメッセージを`$err_msg`という変数にセットしているので、`$err_msg`を判定するようにしています😊

```php
    if (empty($msg)) {
        $err_msg = '年齢を入力してください';
    }
```

2022-09-03 05:39 UTC, kazu-taka commented on 06/04_form.php
> +    echo "{$num1} - {$num2}";
@futaba96 
`$operator = $_GET['operator'];`で変数に代入しているので、あとはif分やswitch文を使用して制御して下さい✨
caseの中でそれぞれ計算するのが良いかと思います😊

```php
// 例
switch ($operator) {
    case '+':
        # ここで足し算実行
        break;
    
    case '-':
        # ここで引き算実行
        break;
    
// 途中省略

    default:
        # code...
        break;
}

2022-09-03 05:45 UTC, kazu-taka commented on 06/05_form.php
> +$num3 = '';
@futaba96 
>変数に変数を代入する際、「$sum = $num1 + $num2 + $num3; 」の書き方のどこがエラーの原因なのかを教えていただきたいです。

ここで文字列として変数を初期化しているので、文字列と文字列は足すことはできませんとメッセージが表示されています。

```php
$sum = $num1 + $num2 + $num3;
```

PHPの計算は、HTMLの前で行った方が良いので、

```php
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $num1 = htmlspecialchars($_POST['number1'], ENT_QUOTES, "UTF-8");
    $num2 = htmlspecialchars($_POST['number2'], ENT_QUOTES, "UTF-8");
    $num3 = htmlspecialchars($_POST['number3'], ENT_QUOTES, "UTF-8");

    // ここで3つの値を足す
}

2022-09-03 05:46 UTC, kazu-taka commented on 06/05_form.php
> +    if (empty($msg)) {
@futaba96 
`$msg`はどこでも代入していないようなので、$num1、$num2、$num3のどれかが未入力時に、`$err_msg`を設定するようにして下さい✨

2022-09-03 05:52 UTC, kazu-taka commented on 06/05_form.php
> +    echo '合計値は' . htmlspecialchars($sum) . 'です';
@futaba96 
あくまでも例ですが、`$err_msg`が空の時に、`echo '合計値は' . htmlspecialchars($sum) . 'です';`を実行すると、常に「合計値は」というメッセージが表示されなくなるので良いと思います✨

2022-09-03 05:55 UTC, kazu-taka commented
@futaba96 
>XSS対策について完全に理解ができないのですが、変数に関数htmlentities()を代入するということでしょうか？
また、変数が複数ある場合は、全ての変数にhtmlentities()を利用するべきなのでしょうか？

`htmlspecialchars()`関数のことですね！
変数が複数ある場合は、それぞれhtmlspecialchars($a)、htmlspecialchars($b)のように関数に渡す必要があります✨
ただし、複数の変数を結合してメッセージを表示するような場合は、`htmlspecialchars($a . 'は' . $b . 'です')`とやっても良いです😊

2022-09-03 08:25 UTC, futaba96 commented on 06/04_form.php
> +    echo "{$num1} - {$num2}";
こちら解決できました！ありがとうございます！
再提出をした際に確認お願いします🙏

2022-09-03 08:25 UTC, futaba96 commented on 06/05_form.php
> +$num3 = '';
ありがとうございます！
if文の中で計算をするようにしても、エラーになってしまいます😭
再提出をしますので一度確認をお願いします😭

2022-09-03 08:26 UTC, futaba96 commented on 06/05_form.php
> +    if (empty($msg)) {
$msgはわかりにくくなってしまうので削除して、$num1、$num2、$num3を代入したので確認お願いします。

2022-09-03 08:26 UTC, futaba96 commented on 06/05_form.php
> +    echo '合計値は' . htmlspecialchars($sum) . 'です';
ありがとうございます！解決できました🙏🙏

2022-09-03 12:47 UTC, kazu-taka requested changes
@futaba96 
コメントしたので確認お願いします😊

2022-09-03 12:47 UTC, kazu-taka commented on 06/01_form.php
> +    $msg = htmlspecialchars($_POST['age'], ENT_QUOTES, "UTF-8");
@futaba96 
ここは年齢を代入するので、$ageの方が良いと思います✨

2022-09-03 12:47 UTC, kazu-taka commented on 06/01_form.php
> +    if (isset($_POST['age']))
@futaba96 
せっかく変数に代入しているので、変数に値が代入されていたらという条件の方が良いと思います✨
変数を$ageに修正したとして解説します！
`$age = ''`で初期化しているため、`isset($age)`にしてしまうと、trueと判断されてしまうため、`if (!empty($age))`で判定するのが良いと思います✨

参考
https://qiita.com/shinichi-takii/items/00aed26f96cf6bb3fe62

2022-09-03 12:47 UTC, kazu-taka commented on 06/02_result.php
> +echo '<br><br><a href="' . $_SERVER['HTTP_REFERER'] . '">戻る</a>';
@futaba96 
aタグで戻るリンクを作成するので、以下の処理の最後にHTMLを書いて、そこにaタグで戻るリンクを作るのが良いです😊
その際に、戻る部分は`02_form.php`を決まっているので、そちらの値をhref属性に指定して下さい✨
```php
<?php

$names = $_POST['message'];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    echo '私の名前は' . htmlspecialchars($names) . 'です';
}
?>

ここにHTMLを記述
```

2022-09-03 12:47 UTC, kazu-taka commented on 06/03_form.php
> +    ?>
@futaba96 
`$_POST['age']`は`$age`に代入しているので、判断する場合は変数を判断するようにして下さい✨
また、`$age`に値が代入されている場合は、`$err_msg`が必ず空になっているので、`$err_msg`が空だったら(`empty($err_msg)`)年齢を出力するか、もしくは`$age`が空以外(`!empty($age)`)の時に年齢を出力するのが良いと思います！

以下は例です😊
```php
    <?php if (empty($err_msg) : ?>
        <p>私は<?= htmlspecialchars($age, ENT_QUOTES, 'UTF-8') ?>歳です</p>
    <?php endif; ?>
```

2022-09-03 12:47 UTC, kazu-taka commented on 06/04_form.php
> +}
@futaba96 
コードが綺麗でいいですね✨

2022-09-03 12:47 UTC, kazu-taka commented on 06/05_form.php
> +    $sum += $num1; $num2; $num3;
@futaba96 
全ての合計を求めるので、`$sum = $num1 + $num2 + $num3;`になります✨

2022-09-03 12:47 UTC, kazu-taka commented on 06/05_form.php
> +    $num3 = htmlspecialchars($_POST['number3'], ENT_QUOTES, "UTF-8");
@futaba96 
ここでは以下のような書き方でOKです！
最終的にHTMLに出力する時に`htmlspecialchars`関数を使用して下さい😊
```php
    $num1 = $_POST['num1'];
    $num2 = $_POST['num2'];
    $num3 = $_POST['num3'];
```

2022-09-03 12:47 UTC, kazu-taka commented on 06/05_form.php
> +if (empty($num1 || $num2 || $num3)) {
@futaba96 
emptyだと数字かどうか判定できないので、`is_numeric`関数を使用して、数字かどうか判断してみて下さい✨

参考
https://www.tairaengineer-note.com/php-isnumeric/

2022-09-03 12:47 UTC, kazu-taka commented on 06/05_form.php
> +            <?php if (is_numeric($num1 && $num2 && $num3)) : ?>
@futaba96 
`$err_msg`を出力する部分になるので、`!empty($err_msg)`で判定した方が良いです✨

2022-09-03 12:47 UTC, kazu-taka commented on 06/05_form.php
> +    echo '合計値は' . htmlspecialchars($sum) . 'です';
@futaba96 
こちらの部分は以下のように、`$sum`が空以外と判定するか、`$err_msg`が空だったらと判断するのが良いと思います✨

例
```php
    <?php if (!empty($sum)) : ?>
        <p>合計値は <?= htmlspecialchars($sum, ENT_QUOTES, 'UTF-8') ?>です</p>
    <?php endif; ?>
```

2022-09-04 00:48 UTC, futaba96 commented on 06/01_form.php
> +    $msg = htmlspecialchars($_POST['age'], ENT_QUOTES, "UTF-8");
ありがとうございます😊修正しました。

2022-09-04 00:51 UTC, futaba96 commented on 06/01_form.php
> +    if (isset($_POST['age']))
ご丁寧に説明いただきありがとうございます😭
修正できました🌟

2022-09-04 00:51 UTC, futaba96 commented on 06/02_result.php
> +echo '<br><br><a href="' . $_SERVER['HTTP_REFERER'] . '">戻る</a>';
ありがとうございます🙏
修正をしたので確認お願いします！

2022-09-04 00:58 UTC, futaba96 commented on 06/03_form.php
> +    ?>
とてもわかりやすい説明をしていただきありがとうございます😭🙏
おかげさまで理解することができました😭
修正をしたので確認お願いします！

2022-09-04 00:59 UTC, futaba96 commented on 06/04_form.php
> +}
ありがとうございます😆🌟

2022-09-04 01:01 UTC, futaba96 commented on 06/05_form.php
> +            <?php if (is_numeric($num1 && $num2 && $num3)) : ?>
かしこまりました！修正済みです！ありがとうございます🙏

2022-09-04 01:06 UTC, futaba96 commented on 06/05_form.php
> +    $sum += $num1; $num2; $num3;
ありがとうございます✨
こちら修正をしたのですが、空欄で送信をすると修正をした行がエラーになってしまいます。。
エラーの意味を調べてみたのですが、自分ではわからず。。どのようなエラーなのでしょうか？
<img width="1137" alt="スクリーンショット 2022-09-04 10 04 44" src="https://user-images.githubusercontent.com/108456982/188292769-a94388d0-25d8-4973-9eba-29eafcfb4176.png">

2022-09-04 01:09 UTC, futaba96 commented on 06/05_form.php
> +if (empty($num1 || $num2 || $num3)) {
ありがとうございます🌟
is_numeric関数を使用して修正しました。
ご確認お願いします。

2022-09-04 01:10 UTC, futaba96 commented on 06/05_form.php
> +    echo '合計値は' . htmlspecialchars($sum) . 'です';
修正をしました！ありがとうございます🙏

2022-09-04 04:04 UTC, kazu-taka requested changes
@futaba96 
1箇所だけコメントしたので確認お願いします😊

2022-09-04 04:04 UTC, kazu-taka commented on 06/05_form.php
> +if (!is_numeric($num1 || $num2 || $num3)) {
@futaba96 
ここは1つ1つ判断した方が良いので、`!is_numeric($num1) || !is_numeric($num2) || !is_numeric($num3)`のように判断して下さい✨
もしくは以下のようにして、今は上で計算している部分(`$sum = $num1 + $num2 + $num3;`)を、以下のように、全て数値だった場合に結合する方が良いと思います！
全て数値のときに計算することにより、文字列等を入力された時に、エラーが発生するリスクがなくなります✨

```php
    if (is_numeric($num1) && is_numeric($num2) && is_numeric($num3)) {
        $sum = $num1 + $num2 + $num3;
    } else {
        $err_msg = 'すべてに数字を入力してください';
    }
```

2022-09-04 04:23 UTC, futaba96 commented on 06/05_form.php
> +if (!is_numeric($num1 || $num2 || $num3)) {
ご丁寧に説明いただきありがとうございます😭
修正をしました。確認お願いします🙏

2022-09-04 05:40 UTC, kazu-taka commented
@futaba96 
問題ないのでマージしてOKです👍
![LGTM](https://image.lgtmoon.dev/21383)

2022-09-04 06:43 UTC, merged